### ISSUE TITLE
Is this Connector working for odoo v8?

### ISSUE THREAD

**Issue by jtb0** [Trust-Code/connector-woocommerce#1]
Hi,

I am not sure about this plugin. Is this only a framework to develop a bidirectional connector, or is this already working?

And if this is working, for which version.

Thank you,

**Comment by niltorrano** [comment]
In our case it has worked for Odoo 8, I think for Odoo 9 it does not work.
I have encountered problems importing provinces and characters from Spanish.

**Comment by danimaribeiro** [comment]
I didn't finish this connector.
This one is fully implemented - https://github.com/OCA/connector-woocommerce
